name: flutter_ast
description: A Pure Dart File to Ast Serializer/Deserializer.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build_cli_annotations: ^1.0.0
  analyzer: any
  path: ^1.7.0
  console: ^3.1.0
  mustache_template: ^1.0.0+1
  recase: ^3.0.0
  # _fe_analyzer_shared: ^9.0.0

dev_dependencies:
  build_runner: any
  build_cli: ^1.3.9
